name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: test on Node.js LTS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v3